### ISSUE TITLE
UX and design revamp

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#151]
Noah: I'd like him to look at UX and make banners for signup, homepage, and accounts.

**Comment by harlantwood** [comment]
- [ ] UX review 
- [ ] banner for signup
- [ ] banner for homepage
- [ ] banner for accounts

**Comment by harlantwood** [comment]
- emojis
- check out various characters
  - hyphen
  - http://jrgraphix.net/r/Unicode/2500-257F

**Comment by harlantwood** [comment]
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Proposal: *MORE HAWAII VACATIONS​*

The effect necessitated the appearance of a realistic front page, which consisted of a main headline relevant to the plot, and several smaller headlines used as filler. A large number of these spinning newspapers included stories titled "New Petitions Against Tax" and "Building Code Under Fire."
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
http://img0.mxstatic.com/wallpapers/5314e2794404342f45cefbecc12ed0cc_large.jpeg?347884887

1: Vote Up
2: View All Solutions
3: Submit Solution
4: Set Reward
b: Back

```To take an action, simply enter the number or letter at the beginning of the line.```

**Comment by harlantwood** [comment]
red fenced code blocks for all direct responses before menus, eg:

`Your vote has been recorded.`

**Comment by harlantwood** [comment]
attachment API -- https://api.slack.com/docs/attachments

**Comment by harlantwood** [comment]
Home: ​*CITIZEN CODE*​

​*View Current Proposals*​
A: more hawaii vacations
B: more naps
C: more kittens

​*Actions*​
1: Create a proposal
2: My balance
3: Cap table
4: More commands

To take an action, simply enter the number or letter at the beginning of the line.

**Comment by harlantwood** [comment]
`<` for back ???

**Comment by harlantwood** [comment]
example attachment code: https://gist.github.com/harlantwood/dbbfcee55c2946029d74

**Comment by aquabu** [comment]
The most tricky bit to sort out is the initial interactions for:
1. admin instance setup and default community for slack instance
2. users first interaction with swarmbot (which community?)
3. user changing their community
4.- user interacting with multiple communities

1 and 2 are *the most important* UX questions because they are the top of the funnel for using swarmbot and will influence our engagement massively. They are the difference between no one using it and people trying it and giving us more feedback / opportunity to interact.

**Comment by harlantwood** [comment]
split out a bunch of stories from this one.  closing this issue.
