### ISSUE TITLE
PM the potential awardee if they don't have a bitcoin address

### ISSUE THREAD

**Issue by dukedorje** [citizencode/swarmbot#258]
Would be a better experience if swarmbot also PMs the potential awardee telling them they are going to get an award, but they don't have a bitcoin address.

**Comment by aquabu** [comment]
Admin tries to award a project coin.

In a private channel with swarmbot the user who has not yet messaged with swarmbot receives the message:

- [ ] "Hi! @username is trying to send you project coins for "Project Name". In order to receive project coin awards please enter your bitcoin address.

**Comment by aquabu** [comment]
If I am already talking with slack I should get a different message. For example the UX for this doesn't make sense.

**Comment by aquabu** [comment]
![screen shot 2015-12-18 at 10 13 31 am](https://cloud.githubusercontent.com/assets/7595/11903799/7b9aff88-a570-11e5-9433-acd352921412.png)

For the message to make sense in this context it would need to say something like:
"Hi! @noah is trying to send you project coins for 'T project'. In order to receive project coin awards please set your bitcoin address from the "All Projects" menu."

This is different than the situation where the user hasn't yet interacted with the bot. We may want to discuss.

**Comment by harlantwood** [comment]
yes, let's discuss

**Comment by gleenn** [comment]
Discussion would be great. There are only 2 cases we have covered:
- never seen user
- user who has interacted (and therefore should be in firebase) but who doesn't have a bitcoin address set
What case is it exactly we are missing?
