### ISSUE TITLE
Logged in user can edit their project on the website

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#341]

**Comment by violasong** [comment]
Edit mode (after clicking Edit Project and authenticating with Slack OAuth)
- Description field grows to fit text

![editmode01x](https://cloud.githubusercontent.com/assets/55994/12971951/968a94ec-d055-11e5-8595-fc3e4c03dd7d.png)

View mode (viewable by anyone with hash URL)

![editproject01x](https://cloud.githubusercontent.com/assets/55994/12971931/563baf20-d055-11e5-9596-e6e94481fd47.png)

**Comment by violasong** [comment]
Updates: drone -> quadcopter, reward -> award, fixed graph, added Send buttons that take you to slack (little placeholder icons to be replaced by either a nice coin icon or emoji, if we're going to support short emoji coin awarding messages).

https://projects.invisionapp.com/d/main#/console/6341574/136215823/preview

I tested the idea of embedding slack via iframe, but I get this error:
`Refused to display 'https://citizencode.slack.com/messages/@devbot/team/devbot/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`
