### ISSUE TITLE
First contact for users in slack

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#349]
See the contact part of this previous story.
https://github.com/citizencode/swarmbot/issues/211

**Comment by violasong** [comment]
In Slack:

<img width="634" alt="screen shot 2016-02-11 at 12 23 00 pm" src="https://cloud.githubusercontent.com/assets/55994/12989395/3f61bc8a-d0ba-11e5-8144-d7fce6025086.png">

On Web:

* Since we're dealing with such large coin values, it would be great if the fields automatically insert commas

![newproject01x](https://cloud.githubusercontent.com/assets/55994/12989890/335113f8-d0bc-11e5-970d-e85b3a785b6c.png)
